name: Build

on:
  push:
    branches:
      - master

jobs:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_arm64'
    - name: Generate build files
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build