name: Release Windows

on:
  release:
    types: [created]

env:
  BUILD_TYPE: Release

jobs:
  build:
      runs-on: windows-2019
      steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
      - name: Generate build files
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Run windeployqt
        run: ..\Qt\6.5.2\msvc2019_64\bin\windeployqt.exe build\Release\coffee.exe
      - name: Zip
        run: 7z a -tzip -mx=9 -mfb=258 -mpass=15 -r coffee.zip build\Release\
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: coffee.zip

